<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>QikLog.Core.Tests</RootNamespace>
    <AssemblyName>QikLog.Core.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\QikLog.Core\QikLog.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
  </ItemGroup>
</Project>
