<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <WarningsNotAsErrors>CS1591</WarningsNotAsErrors>
    <Company>QikLog</Company>
    <Authors>Jamey McElveen</Authors>
    <Copyright>Copyright © Jamey McElveen $([System.DateTime]::Now.Year)</Copyright>
  </PropertyGroup>
</Project>
