server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    include /etc/nginx/mime.types;

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }

    types {
        image/vnd.microsoft.icon ico;
        application/manifest+json webmanifest;
    }
}
